Demohand b coupled joints
shadow-robot/sr-config pull request #144
Opened 2019-09-16 10:20 UTC by mikramarc

2019-09-17 16:31 UTC, toliver requested changes

2019-09-17 16:31 UTC, toliver commented on sr_ethercat_hand_config/calibrations/rh/calibration.yaml
> +  [["THJ1", "THJ2"], [[[2738, 2301], 0.0, 0.6981],
Let's use degrees for the values that are now in radians.

2019-09-17 16:31 UTC, toliver commented on sr_ethercat_hand_config/calibrations/rh/calibration.yaml
> +  [["THJ1", "THJ2"], [[[2738, 2301], 0.0, 39.99818],
Please round up the numbers ;)
The calibration points are defined by us in degrees. See the numbers in the old calibration above.

2020-04-28 10:13 UTC, giusebar approved these changes

2020-04-28 10:13 UTC, merged