F#src src 602 update yaml fields
shadow-robot/sr-config pull request #73
Opened 2017-08-09 13:02 UTC by dg-shadow

2017-08-09 13:18 UTC, toliver requested changes

2017-08-09 13:18 UTC, toliver commented on sr_ethercat_hand_config/controls/motors/lh/motor_board_effort_controllers.yaml
> +    torque_limit: 500
Please check with @jlaforga but I think the torque limit should be the same as in the old imax (550 in this case).

Not sure why we reduced it in our June delivery.

2017-08-09 14:55 UTC, dg-shadow commented on sr_ethercat_hand_config/controls/motors/lh/motor_board_effort_controllers.yaml
> +    torque_limit: 500
I copied the values from right->left, so this means the old left hand had a value different to the right. I suspect they should be the same. @jlaforga - can you answer this?

2017-08-10 08:00 UTC, toliver commented on sr_ethercat_hand_config/controls/motors/rh/motor_board_effort_controllers.yaml
> +    torque_limit: 500
But here it is also happening. 550 vs 500

2017-08-10 08:00 UTC, toliver commented on sr_ethercat_hand_config/controls/motors/rh/motor_board_effort_controllers.yaml
> +    max_pwm: 400
And here max_pwm has changed.

2017-08-10 08:01 UTC, toliver commented on sr_ethercat_hand_config/controls/motors/rh/motor_board_effort_controllers.yaml
> +    torque_limit: 450
Although to be honest 450 seems more sensible than 700.

2017-08-10 09:09 UTC, jlaforga commented on sr_ethercat_hand_config/controls/motors/lh/motor_board_effort_controllers.yaml
> +    torque_limit: 500
Hello,
These values are estimations that we've been using historically and we didn't have problems with, I provided them to Dan. The only thing I would like to change is the TH1  & TH2 to 400, I 've just remember that OpenAI had 450 and the T-bar broke, so let's going to reduce TH1 and TH2 torque_limit to 400. The rest of the values should be OK.
Cheers,

2017-08-14 10:13 UTC, merged